services:
  app:
    image: ghcr.io/studal-org/app:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_DB}"
      AGENT_COLLEGE_URL: $AGENT_COLLEGE_URL
      AGENT_COLLEGE_USERNAME: $AGENT_COLLEGE_USERNAME
      AGENT_COLLEGE_PASSWORD: $AGENT_COLLEGE_PASSWORD
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_USERNAME: $SMTP_USERNAME
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_FROM: $SMTP_FROM
      SESSION_SECRET: $SESSION_SECRET
      SESSION_TTL: $SESSION_TTL
      APP_INTERNAL_KEY: $APP_INTERNAL_KEY
      APP_URL: $APP_URL
      APP_TZ: $APP_TZ
  postgres:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_DB}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: