/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ScheduleForDate/{id}": {
    /** Read ScheduleForDate by ID */
    get: operations["get-ScheduleForDate"];
  };
  "/ScheduleForDate/FindByScheduleDate": {
    /** Find ScheduleForDate by scheduleDate */
    get: operations["get-ScheduleForDate-FindByScheduleDate"];
  };
  "/PeriodsSchedule/{id}": {
    /** Read PeriodsSchedule by ID */
    get: operations["get-PeriodsSchedule"];
  };
  "/Individual/{id}": {
    /** Read Individual by ID */
    get: operations["get-Individual-id"];
  };
  "/Individual/FindByEmail": {
    /** Find Individual by email */
    get: operations["get-Individual-FindByEmail"];
  };
  "/Individual/{id}/Student": {
    /** Read Student by Individual ID */
    get: operations["get-Individual-id-Student"];
  };
  "/Indivudial/{id}/Administrator": {
    /** Read Administrator by Individual ID */
    get: operations["get-Indivudial-id-Administrator"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** ScheduleForDate */
    ScheduleForDate: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      periodScheduleId?: string;
      /** Format: date */
      scheduleDate?: string;
    };
    /** ScheduleForDate_ByScheduleDate */
    ScheduleForDate_ByScheduleDate: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      periodScheduleId?: string;
      /** Format: date */
      scheduleDate: string;
    };
    /** PeriodsSchedule */
    PeriodsSchedule: {
      /** Format: uuid */
      id: string;
      name: string;
      schedule?: {
        periodNumber?: number;
        /** Format: time */
        startTime?: string;
        /** Format: time */
        endTime?: string;
      }[];
    };
    /** Individual */
    Individual: {
      id: string;
      fullName?: string;
      email?: string;
    };
    /** Individual_ByEmail */
    Individual_ByEmail: {
      id: string;
      fullName?: string;
      email: string;
    };
    /** Student */
    Student: {
      id: string;
      individualId: string;
    };
    /** Administrator */
    Administrator: {
      id: string;
      individualId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Read ScheduleForDate by ID */
  "get-ScheduleForDate": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleForDate"];
        };
      };
      /** @description Not Found */
      404: {
        content: never;
      };
    };
  };
  /** Find ScheduleForDate by scheduleDate */
  "get-ScheduleForDate-FindByScheduleDate": {
    parameters: {
      query?: {
        scheduleDate?: string;
      };
    };
    requestBody?: {
      content: {
        "*/*": never;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleForDate_ByScheduleDate"];
        };
      };
      /** @description Not Found */
      404: {
        content: never;
      };
    };
  };
  /** Read PeriodsSchedule by ID */
  "get-PeriodsSchedule": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PeriodsSchedule"];
        };
      };
      /** @description Not Found */
      404: {
        content: never;
      };
    };
  };
  /** Read Individual by ID */
  "get-Individual-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Individual"];
        };
      };
      /** @description Not Found */
      404: {
        content: never;
      };
    };
  };
  /** Find Individual by email */
  "get-Individual-FindByEmail": {
    parameters: {
      query: {
        email: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Individual_ByEmail"];
        };
      };
      /** @description Not Found */
      404: {
        content: never;
      };
    };
  };
  /** Read Student by Individual ID */
  "get-Individual-id-Student": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Student"];
        };
      };
      /** @description Not Found */
      404: {
        content: never;
      };
    };
  };
  /** Read Administrator by Individual ID */
  "get-Indivudial-id-Administrator": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Administrator"];
        };
      };
      /** @description Not Found */
      404: {
        content: never;
      };
    };
  };
}
