/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/ScheduleForDate/{id}": {
    /** Read ScheduleForDate by ID for groupId */
    get: operations["get-ScheduleForDate-ForGroupId"];
  };
  "/ScheduleForDate/FindByScheduleDate": {
    /** Find ScheduleForDate by scheduleDate for groupId */
    get: operations["get-ScheduleForDate-FindByScheduleDate-ForGroupId"];
  };
  "/PeriodsSchedule/{id}": {
    /** Read PeriodsSchedule by ID */
    get: operations["get-PeriodsSchedule"];
  };
  "/PeriodsSchedule/Default": {
    /** Read default PeriodsSchedule */
    get: operations["get-PeriodsSchedule-Default"];
  };
  "/Individual/{id}": {
    /** Read Individual by ID */
    get: operations["get-Individual-id"];
  };
  "/Individual/FindByEmail": {
    /** Find Individual by email */
    get: operations["get-Individual-FindByEmail"];
  };
  "/Individual/{id}/Student": {
    /** Read Student by Individual ID */
    get: operations["get-Individual-id-Student"];
  };
  "/Individual/{id}/Administrator": {
    /** Read Administrator by Individual ID */
    get: operations["get-Individual-id-Administrator"];
  };
  "/Student/{id}": {
    /** Read Student by ID */
    get: operations["get-Student-id"];
  };
  "/Student/{id}/Performance": {
    /** Read Student Performance by Student ID by Period */
    get: operations["get-Student-id-Marks-ByPeriod"];
  };
  "/Discipline/{id}": {
    /** Read Discipline by ID */
    get: operations["get-Discipline-id"];
  };
  "/PracticeKind/{id}": {
    /** Read PracticeKind by ID */
    get: operations["get-PracticeKind-id"];
  };
  "/ControlType/{id}": {
    /** Read ControlType by ID */
    get: operations["get-Control-Type-id"];
  };
  "/WorkType/{id}": {
    /** Read WorkType by ID */
    get: operations["get-Work-Type-id"];
  };
  "/Classroom/{id}": {
    /** Read Classroom by ID */
    get: operations["get-Classroom-id"];
  };
  "/Employee/{id}": {
    /** Read Employee by ID */
    get: operations["get-Employee-id"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Period */
    Period_AsItem: {
      number: number;
      groupId: string | null;
      subgroup: number | null;
      periodNumber: number | null;
      discipline: ({
        /** @enum {string} */
        objectType: "discipline" | "practiceKind";
        /** Format: uuid */
        objectId: string;
      }) | null;
      teacherId: string | null;
      classroomId: string | null;
      workTypeId: string | null;
    };
    /** ScheduleForDate */
    ScheduleForDate: {
      /** Format: uuid */
      id: string;
      scheduleDate: string | null;
      periodScheduleId: string | null;
      schedule: components["schemas"]["Period_AsItem"][];
    };
    /** ReferenceNotFoundError */
    ReferenceNotFound: {
      /** @constant */
      code: "ReferenceNotFound";
      message: string;
      referenceType: string;
    };
    /** ScheduleForDate_ByScheduleDate */
    ScheduleForDate_ByScheduleDate: {
      /** Format: uuid */
      id: string;
      /** Format: date */
      scheduleDate: string;
      periodScheduleId: string | null;
      schedule: components["schemas"]["Period_AsItem"][];
    };
    /** NotFoundError */
    NotFound: {
      /** @constant */
      code: "NotFound";
      message: string;
    };
    /** PeriodsSchedule */
    PeriodsSchedule: {
      /** Format: uuid */
      id: string;
      name: string;
      schedule: ({
          periodNumber: number | null;
          startTime: string | null;
          endTime: string | null;
        })[];
    };
    /** Individual */
    Individual: {
      id: string | null;
      fullName: string | null;
      email: string | null;
      name: {
        first: string;
        middle: string;
        last: string;
      } | null;
    };
    /** Individual_ByEmail */
    Individual_ByEmail: {
      /** Format: uuid */
      id: string;
      fullName: string | null;
      email: string;
      name: {
        first: string;
        middle: string;
        last: string;
      } | null;
    };
    /** Student */
    Student_ByIndividual: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      individualId: string;
      groupId: string | null;
    };
    /** Administrator */
    Administrator_ByIndividual: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      individualId: string;
    };
    /** Student */
    Student: {
      /** Format: uuid */
      id: string;
      individualId: string | null;
      groupId: string | null;
    };
    /** Mark */
    Mark: {
      number: number;
      mark: number;
      /** Format: uuid */
      controlTypeId: string;
    } | {
      number: number;
      isPassed: boolean;
      /** Format: uuid */
      controlTypeId: string;
    };
    /** StudentPerformance */
    StudentPerformance: {
      /** @enum {string} */
      objectType: "statement" | "retakeReferral" | "stateCertificationBoardProtocol" | "practiceReport" | "incomingAcademicCertificate" | "additionalClass" | "class";
      /** Format: uuid */
      objectId: string;
      /** Format: date-time */
      date: string;
      discipline: {
        /** @enum {string} */
        objectType: "discipline" | "practiceKind";
        /** Format: uuid */
        objectId: string;
      };
      workTypeId: string | null;
      controlTypeId: string | null;
      isLate: boolean | null;
      isAttended: boolean | null;
      marks: components["schemas"]["Mark"][];
    };
    /** Discipline */
    Discipline: {
      /** Format: uuid */
      id: string;
      title: string;
      shortTitle: string;
      fullTitle: string | null;
    };
    /** Practice Kind */
    PracticeKind: {
      /** Format: uuid */
      id: string;
      practiceType: ("educational" | "internship" | "undergraduate") | null;
      title: string;
      shortTitle: string;
      fullTitle: string | null;
    };
    /** ControlType */
    ControlType: {
      /** Format: uuid */
      id: string;
      title: string;
      markTypeId: string | null;
    };
    /** WorkType */
    WorkType: {
      /** Format: uuid */
      id: string;
      title: string;
    };
    /** Classroom */
    Classroom: {
      id: string;
      title: string;
      number: number;
    };
    /** Employee */
    Employee: {
      /** Format: uuid */
      id: string;
      individualId: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Read ScheduleForDate by ID for groupId */
  "get-ScheduleForDate-ForGroupId": {
    parameters: {
      query?: {
        groupId?: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleForDate"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Find ScheduleForDate by scheduleDate for groupId */
  "get-ScheduleForDate-FindByScheduleDate-ForGroupId": {
    parameters: {
      query: {
        scheduleDate: string;
        groupId: string;
      };
    };
    requestBody?: {
      content: {
        "*/*": never;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ScheduleForDate_ByScheduleDate"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"] | components["schemas"]["NotFound"];
        };
      };
    };
  };
  /** Read PeriodsSchedule by ID */
  "get-PeriodsSchedule": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PeriodsSchedule"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read default PeriodsSchedule */
  "get-PeriodsSchedule-Default": {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PeriodsSchedule"];
        };
      };
    };
  };
  /** Read Individual by ID */
  "get-Individual-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Individual"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Find Individual by email */
  "get-Individual-FindByEmail": {
    parameters: {
      query: {
        email: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Individual_ByEmail"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["NotFound"];
        };
      };
    };
  };
  /** Read Student by Individual ID */
  "get-Individual-id-Student": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Student_ByIndividual"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"] | components["schemas"]["NotFound"];
        };
      };
    };
  };
  /** Read Administrator by Individual ID */
  "get-Individual-id-Administrator": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Administrator_ByIndividual"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"] | components["schemas"]["NotFound"];
        };
      };
    };
  };
  /** Read Student by ID */
  "get-Student-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Student"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read Student Performance by Student ID by Period */
  "get-Student-id-Marks-ByPeriod": {
    parameters: {
      query: {
        periodStart: string;
        periodEnd: string;
      };
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["StudentPerformance"][];
        };
      };
      /** @description Bad Request */
      400: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read Discipline by ID */
  "get-Discipline-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Discipline"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read PracticeKind by ID */
  "get-PracticeKind-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["PracticeKind"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read ControlType by ID */
  "get-Control-Type-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["ControlType"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read WorkType by ID */
  "get-Work-Type-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["WorkType"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read Classroom by ID */
  "get-Classroom-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Classroom"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
  /** Read Employee by ID */
  "get-Employee-id": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["Employee"];
        };
      };
      /** @description Not Found */
      404: {
        content: {
          "application/json": components["schemas"]["ReferenceNotFound"];
        };
      };
    };
  };
}
